/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_pankaj_assassins_DetectionBasedTracker */

#ifndef _Included_com_pankaj_assassins_DetectionBasedTracker
#define _Included_com_pankaj_assassins_DetectionBasedTracker
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_pankaj_assassins_DetectionBasedTracker
 * Method:    nativeInitLoaders
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_pankaj_assassins_DetectionBasedTracker_nativeInitLoaders
  (JNIEnv *, jclass, jstring jpathVariable);

/*
 * Class:     com_pankaj_assassins_DetectionBasedTracker
 * Method:    nativeCollect
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_com_pankaj_assassins_DetectionBasedTracker_nativeCollect
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_pankaj_assassins_DetectionBasedTracker
 * Method:    nativeTrain
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_pankaj_assassins_DetectionBasedTracker_nativeTrain
  (JNIEnv *, jclass);

/*
 * Class:     com_pankaj_assassins_DetectionBasedTracker
 * Method:    nativeRecognize
 * Signature: (JJ)V
 */
JNIEXPORT jint JNICALL Java_com_pankaj_assassins_DetectionBasedTracker_nativeRecognize
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_pankaj_assassins_DetectionBasedTracker
 * Method:    nativeReset
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_pankaj_assassins_DetectionBasedTracker_nativeReset
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
